# Generated by Django 3.2.4 on 2021-06-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='user',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
