# Generated by Django 3.2.4 on 2021-06-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_email_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='user',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
