# Generated by Django 3.2.4 on 2021-06-23 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_alter_email_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='archived',
        ),
    ]
