# Generated by Django 3.2.4 on 2021-06-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0008_alter_email_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='gmail_id',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
