# Generated by Django 3.2.4 on 2021-06-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0009_email_gmail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='timestamp',
            field=models.DateTimeField(blank=True),
        ),
    ]
